
declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: string;
    NEXT_PUBLIC_ERPNEXT_API_URL: string;
    ERPNEXT_GUEST_API_KEY: string;
    ERPNEXT_GUEST_API_SECRET: string;
    XENDIT_SECRET_KEY: string;
    XENDIT_CALLBACK_VERIFICATION_TOKEN: string;
    IPAYMU_VA: string;
    IPAYMU_API_KEY: string;
    NEXT_PUBLIC_IPAYMU_SANDBOX_MODE: string;
  }
}
