version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flarebee
    ports:
      - "9003:9003"
    volumes:
      # Mounts the current directory into /app in the container for hot-reloading
      - .:/app
      # Use a named volume for node_modules to avoid overwriting them
      - node_modules:/app/node_modules
      # Mount the .next folder to persist build cache
      - ./.next:/app/.next
    command: npm run dev
    # Pass environment variables from a .env file into the container
    env_file:
      - .env

# Define the named volume for node_modules
volumes:
  node_modules:
